# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - django-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Check Django project
        run: |
            cd demo-code
            source myenv/bin/activate
            python demo-code/manage.py check
  

      - name: Collect static files
        run: |
            cd demo-code
            poetry run python ./manage.py collectstatic --noinput
        
      - name: Install dependencies
        run: |
          source myenv/bin/activate 
          pip install --upgrade pip
          pip install -r demo-code/requirements.txt 
    
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: python-app

        - name: Unzip artifact for deployment
          run: unzip release.zip

        
        - name: Login to Azure
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_667A3AC9DA894ECAA35BF61CB474A56A }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C96B97C3963740E2B12FAA668267325A }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ABA06D97C1744CC4B246A565254B21D1 }}

        - name: 'Deploy to Azure Web App'
          uses: azure/webapps-deploy@v2
          id: deploy-to-webapp
          with:
            app-name: 'django-test'
            slot-name: 'Production'
              